export const ROUTES = {
  // HOME_PAGE: "/",
  DASHBOARD_PAGE: "/",
  DISPLAY_CATEGORY: "/category/display-category",
  CREATE_CATEGORY: "/category/create-category",
  UPDATE_CATEGORY: "/category/update-category",
  DISPLAY_PRODUCT: "/product/display-product",
  CREATE_PRODUCT: "/product/create-product",
  MANAGE_IMPORT: "/product/manage-import",
  CREATE_MANAGE_IMPORT: "/product/create-manage-import",
  UPDATE_MANAGE_IMPORT: "/product/update-manage-import",
  UPDATE_PRODUCT: "/product/update-product",
  DISPLAY_ORDER: "/order/display-order",
  DETAIL_ORDER: "/order/detail-order",
  UPDATE_ORDER: "/order/update-order",
  DISPLAY_VOUCHER: "/voucher/display-voucher",
  CREATE_VOUCHER: "/voucher/create-voucher",
  UPDATE_VOUCHER: "/voucher/update-voucher",
  CUSTOMIZED_PRODUCT: "/customized-product",
  DISPLAY_ORDER_CUSTOMIZED_PRODUCT: "/order/display-order-customized-product",
  UPDATE_ORDER_CUSTOMIZED_PRODUCT: "/order/update-order-customized-product",
}

export const ROUTES_LABEL = {
  HOME_PAGE: "Dashboard",
  CATEGORY_LABEL: "Category",
  DISPLAY_CATEGORY: "List of categories",
  CREATE_CATEGORY: "Create category",
  PRODUCT_LABEL: "Product",
  CUSTOMIZED_PRODUCT_LABEL: "Customized product",
  DISPLAY_PRODUCT: "List of products",
  CREATE_PRODUCT: "Create product",
  MANAGE_IMPORT: "Manage import",
  CREATE_MANAGE_IMPORT: "Create manage import",
  ORDER_LABEL: "Order",
  DISPLAY_ORDER: "Order products",
  DISPLAY_ORDER_CUSTOMIZED_PRODUCT: "Order customized products",
  VOUCHER_LABEL: "Voucher",
  DISPLAY_VOUCHER: "List of vouchers",
  CREATE_VOUCHER: "Create voucher",
}