export const GET_LIST_PRODUCTS = "/products/listProducts"
export const CREATE_PRODUCT = "/products/create"
export const GET_DETAIL_PRODUCT = "/products/detail"
export const UPDATE_DETAIL_PRODUCT = "/products/update"
export const DELETE_DETAIL_PRODUCT = "/products/delete"
export const UPLOAD_PRODUCT = "/upload/upload-cloudinary"